### ISSUE TITLE
_reactNativeFirebase2.default.reset is not a function

### ISSUE THREAD

**Issue by Shinichi52** [rmrs/react-native-redux-firebase-patterns#1]
i tried configure my test same with your example but it's not work. It's show error: _reactNativeFirebase2.default.reset is not a function. How to link react-native-firebase with react-native-firebase file in your project?

**Comment by erezrokah** [comment]
Can you please post you code?
Please notice we're using jest for our tests and we've setup a mock for the library:
https://github.com/rmrs/react-native-redux-firebase-patterns/tree/master/__mocks__

**Comment by Shinichi52** [comment]
it's worked. @erezrokah thanks for fast support. good job :)
